theme: minima

minima:
  skin: dark

title: "Kyle's Resume"
description: "What would you like to know about me?"

author: "Kyle Zsembery"
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Already have a link home
header_pages:
  - contact.md
